---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pihole-secret
  namespace: pihole
spec:
  encryptedData:
    password: AgADJOY7mjMG8SP7C219dqnDOvLIvbGbMAuc4Wg0NKi1G76xFFnfJV9d24ZN9q975ORVuNnA6oszpu+2lcP3zsUq2ia2Hn7TOHJQgDdRqsxPSfFRSJoSTsC4QVd26WzynGrY9lU8XI2EFKq1OFNYDdIbZAJNRjl8yqY8tCQeJi9L19C3nITmVOja0cBQ5VDtP4fDWkk8E98WNeRWumcgr4fC36b+Tj2ZKoFQC8WF/KenCRQ8q7vIGV/RGxbE6+DJyR24znjaHE80njxn8SFxrlQ0bo10imSejvdiamljHd0HBu1YlnqW0nhhrdzmiSz+k7GxuZNRHzvWSRpwYAMdl+Ia6nLuAF/Is1dVdE4hlNRTs3rF0mWCURY5PZ2zdeotLppuumHGz/GlJ2cnwYhCP9lKAMm1fUfD3PNtlzU87RQzcNAVGMnNMOcllg58YX7la+WaqX5J2Ub4Qvu5FJL1DDW9BF2/xXPBj8GI8sA3JMH00ZP4H15ItaAb4U/NBdBhiKizc/T3HIXFgBJ/BEg4HprPQipHW7iUc0OBkn9FNzLRMW2jW1d8eXZa90Fw0eg25OwvkB4nzBQPyTC04dz7ipNFHmfNKnET2KOEsyIhdDeTeN4yUbJBTHpPAEBVghl4QtvyWRHBFaJtNPL8mriRaasg8ljcLpENOZhpCMbJ5B0DL+sRr7RHTTDNpXlkzO8GRNv4FYi257W8tQ==
  template:
    metadata:
      creationTimestamp: null
      name: pihole-secret
      namespace: pihole
