---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: freshrss-pvc-data
  namespace: freshrss
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: freshrss-pvc-extensions
  namespace: freshrss
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
